services:
  web:  
    build:
      context: ./web
      dockerfile: apache&&laravel.Dockerfile
    container_name: apache&&laravel_webserver
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
      - ./web/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - backend
      - frontend
  mariadb:
    image: mariadb:latest
    container_name: mariadb_server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: apiStatistics
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
  cliente:
    build:
      context: ./cliente
      dockerfile: react.Dockerfile
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - ./cliente:/app
    networks:
      - frontend

networks:
  backend:
  frontend: