services:
  web:  
    build:
      context: ./web
      dockerfile: apache&&laravel.dockerfile
    container_name: apacheLaravel_webserver
    volumes:
      - ./web:/var/www/html
      - ./web/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
  mariadb:
    image: mariadb:latest
    container_name: mariadb_server
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: apiStatistics
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
  cliente:
    build:
      context: ./react
      dockerfile: react.dockerfile
    container_name: react_app
    ports:
      - "3000:3000"
    #volumes:
    #  - ./react:/app <-- if i uncomment this line, the react app will not work, because it will not be able to find the node_modules due to overriding the /app directory
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  mariadb_data: